export global Colors := {
    property <color> background1;
    property <color> background2;
    property <color> background3;
    property <color> background4;
}

Test := Window {
    width: 400px;
    height: 400px;

    title: "Random Color";

    callback change-color;
    
    VerticalLayout {
        HorizontalLayout { 
            TouchArea {
                Rectangle {
                    background: Colors.background1;
                }

                clicked => {
                    root.change-color();
                }
            }

            TouchArea {
                Rectangle {
                    background: Colors.background2;
                }

                clicked => {
                    root.change-color();
                }
            }
        }

        HorizontalLayout {
            TouchArea {
                Rectangle {
                    background: Colors.background3;
                }

                clicked => {
                    root.change-color();
                }
            }

            TouchArea {
                Rectangle {
                    background: Colors.background4;
                }

                clicked => {
                    root.change-color();
                }
            }
        }
    }
    TouchArea {
        clicked => {
            self.visible = false;
            root.change-color();
        }

        Rectangle {
            background: black;

            Text {
                text: "Klick mich!";
                font-size: 30px;
                color: white;
                width: 150px;
                height: 60px;
                y: root.height/2-self.height/2;
                x: root.width/2-self.width/2;
            }
        }
    }
}